config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :games do
    collection do
      get :reset
      post :reset
    end
    member do
      post :player_action
      post :next_hand
    end
  end

  # Defines the root path route ("/")
  root "games#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/poker_game_serializable.rb
module PokerGameSerializable
  extend ActiveSupport::Concern

  def initialize(json)
    unless json.blank?
      if json.is_a?(String)
        json = JSON.parse(json)
      end
      # Will only set the properties that have an accessor,
      # such as those provided to an attr_accessor call.
      json.to_hash.each { |k, v| self.public_send("#{k}=", v) }
    end
  end

  class_methods do
    def load(json)
      return nil if json.blank?
      self.new(json)
    end
    def dump(obj)
      # Make sure the type is right.
      if obj.is_a?(self)
        obj.to_json
      else
        # raise StandardException, "Expected #{self}, got #{obj.class}"
        raise "Expected #{self}, got #{obj.class}"
      end
    end
  end
end

app/models/game.rb
# Stores game data
class Game < ApplicationRecord
  serialize :data, Poker::Game
  has_many :game_hands, dependent: :destroy
end

app/models/game_hand.rb
# Manages poker logs for a hand
# Based on: https://en.wikipedia.org/wiki/Hand_history
class GameHand < ApplicationRecord
  belongs_to :game

  def self.log(str, game_id, game_hand_id = nil)
    if game_hand_id
      gl = GameHand.where(game_id: game_id, id: game_hand_id).first
      gl.log ||= ''
      gl.log += str.chomp + "\n"
      gl.save
      gl
    else
      GameHand.create(game_id: game_id, log: str.chomp + "\n")
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  def self.reset!
    Poker::PLAYER_NAMES.each_with_index do |name, idx|
      p = Player.where(name: name).first_or_initialize
      p.slug = name.slugify
      p.save!
      pob = Poker::Player.new(p.id, name)
      p.image_name = pob.image_name
      p.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game

  def index
    @games = Game.all
  end

  # sets gamedb and game in set_game filter
  def show
  end

  def new
    @game = Poker::Game.deal!
    redirect_to game_path(@game.db_id)
  end

  def reset
    Game.destroy_all
    new
  end

  def player_action
    @game.player_action(params[:player_action], amount: params[:amount].to_i)
    redirect_to game_path(@game.db_id)
  end

  def next_game
    @game.next_hand
  end

  def set_game
    return unless params[:id]
    @gamedb = Game.find_by_id(params[:id])
    @game = @gamedb.data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
  CARD_TINY_WIDTH = 30
  CARD_SMALL_WIDTH = 50
  CARD_LARGE_WIDTH = 70

  def fmt_money(amount)
    "$#{amount}"
  end
  module_function :fmt_money # allows use of this outside of views

  def player_table(player_idx)
    render partial: 'player_table', locals: { player_idx: player_idx }
  end

  def player_deets(player_idx)
    render partial: 'player_deets',
           locals: { player_idx: }
  end

  def player_image(player)
    image_tag(player.image_name, width: 70, style: 'border-radius: 50%')
  end

  def player_best_hand(player)
    show_txt_cards(player.best_hand(@game.community_cards))
  end

  def player_hand_rank(player)
    res = player.hand_rank(@game.community_cards)
    "#{res.name}: #{res.score.round(2)}"
  end

  def game_table
    render partial: 'table'
  end

  def game_stats
    render partial: 'stats'
  end

  def small_back_card
    card_image('cards/back.png', width: CARD_SMALL_WIDTH)
  end

  def small_card(card)
    card_image(card.image_name, width: CARD_SMALL_WIDTH)
  end

  def large_back_card
    card_image('cards/back.png', width: CARD_LARGE_WIDTH)
  end

  def large_card(card)
    card_image(card.image_name, width: CARD_LARGE_WIDTH)
  end

  def card_image(card_image_name, width:)
    image_tag(card_image_name,
              width: width,
              border: 1,
              style: 'border-radius: 5%')
  end

  def show_tiny_cards(cards)
    show_cards(cards, width: CARD_TINY_WIDTH)
  end

  def show_small_cards(cards)
    show_cards(cards, width: CARD_SMALL_WIDTH)
  end

  def show_large_cards(cards)
    show_cards(cards, width: CARD_LARGE_WIDTH)
  end

  def show_cards(cards, width:)
    cards.map {|c| card_image(c.image_name, width: width)}.join.html_safe
  end

  def show_txt_cards(cards)
    res = []
    cards.each do |c|
      rank = c.rank
      suit = c.suit
      res << rank
      clr =
        case suit.to_sym
        when :h, :d
          'red'
        else
          'black'
        end
      res << %(<span style="color:#{clr}">#{c.suit_emoji}</span>)
    end
    res.join.html_safe
  end
end

app/views/games/_actions.html.erb
<%
  cb = @game.current_bet + 10
  player = @game.current_player
%>
<ul class='player-actions-list'>
  <% @game.cp_actions.each do |n, h| %>
    <%
      k = h.keys.first
      v = h.values.first
    %>
    <li>
      <% if v < 0 %>
        <i><%= n %></i>
      <% elsif v == 0 %>
        <%= button_to n,
          player_action_game_path(@game.db_id, player_action: k) %>
      <% elsif k == :call %>
        <%= button_to "#{n} #{fmt_money(v)} to #{fmt_money(v + @game.pot)}",
          player_action_game_path(@game.db_id, player_action: :call) %>
      <% else %>
        <%= button_to "#{n} #{fmt_money(v)} to #{fmt_money(v + @game.pot)}",
          player_action_game_path(@game.db_id, player_action: k, amount: v) %>
      <% end %>
    </li>
  <% end %>
  <!--
  <li>
    <%=button_to 'Next Hand', next_hand_game_path(@game.db_id) %>
  </li>
  -->
  <li>
    <%=button_to 'Reset!', reset_games_path %>
  </li>
</ul>

app/views/games/_player_deets.html.erb
<%
  titles, _ = @game.get_titles(player_idx)
  p = @game.players[player_idx]
%>
<%= player_image(p) %>
<ul class='player-deets-list'>
  <li><%= titles.join(' ') %><%= p.name %></li>
  <li>Seat #<%= p.seat %></li>
  <% if p.folded %>
    <li>FOLDED: <%= show_txt_cards(p.hole_cards) %></li>
  <% else %>
    <li><%= fmt_money(p.stack) %></li>
    <% unless (pbh = player_best_hand(p)).blank? %>
      <li><%= pbh %></li>
    <% end %>
    <li><%= player_hand_rank(p) %></li>
    <% if p.last_action.present? %>
      <li><i><%=p.last_action%></i></li>
    <% end %>
    <% if p.current_bet %>
      <li>Bet: <%=fmt_money(p.current_bet)%></li>
    <% end %>
  <% end %>
</ul>

app/views/games/_player_deets_table.html.erb
<%
  titles, _ = @game.get_titles(player_idx)
  p = @game.players[player_idx]
%>
<ul class='player-deets-list'>
  <li><%= titles.join(' ') %><%= p.name %></li>
  <% if p.folded %>
    <li>FOLDED: <%= show_txt_cards(p.hole_cards) %></li>
  <% else %>
    <li><%= fmt_money(p.stack) %></li>
    <% if p.last_action.present? %>
      <li><i><%=p.last_action%></i></li>
    <% end %>
  <% end %>
</ul>

app/views/games/_player_table.html.erb
<%
  _, cnames = @game.get_titles(player_idx)
  p = @game.players[player_idx]
%>

<div class='player-div <%=cnames.join(' ')%>'>
  <%= player_image(p) %>
  <% if p.folded %>
    <%= small_back_card %>
    <%= small_back_card %>
  <% else %>
    <%= small_card(p.hole_card1) %>
    <%= small_card(p.hole_card2) %>
  <% end %>
  <br/>
  <%= render partial: 'player_deets_table',
             locals: { player_idx: } %>
</div>

app/views/games/_stats.html.erb
<h3>Player hand rank</h3>
<ol class='player-hand-ranking'>
  <% @game.rank_players.each do |p| %>
    <li>
      <%= p %>
      <% unless (pbh = player_best_hand(p)).blank? %>
        <br/>(<%= pbh %>)
        <br/><%= player_hand_rank(p) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/games/_table.html.erb
<table>
  <tr valign="bottom">
    <td>&nbsp;</td>
    <td><%= player_table(0) %></td>
    <td><%= player_table(1) %></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><%= player_table(5) %></td>
    <td colspan=2>
      <div class='table'>
        <% @game.community_cards.each do |c| %>
          <%= large_card(c) %>
        <% end %>
        <% (5 - @game.community_cards.size).times do %>
          <%= large_back_card %>
        <% end %>
        <br/>
        <b><%=@game.stage%></b>
        Pot: <%= fmt_money(@game.pot) %>
        Call: <%= fmt_money(@game.cp_call_amt) %>
        Min Raise: <%= fmt_money(@game.current_bet) %>
        <br/>
        <i><%= @game.last_player_action %></i>

        <br/>player_action_cnt: <%= @game.player_action_cnt %>
        <br/>player_total_action_cnt: <%= @game.player_total_action_cnt %>
        <br/>player_all_in_cnt: <%= @game.player_all_in_cnt %>
      </div>
    </td>
    <td><%= player_table(2) %></td>
  </tr>
  <tr valign="top">
    <td>&nbsp;</td>
    <td><%= player_table(4) %></td>
    <td><%= player_table(3) %></td>
    <td>&nbsp;</td>
  </tr>
</table>

app/views/games/index.html.erb
<ul>
  <li><%=link_to 'new', new_game_path %></li>
  <li><%=link_to 'reset', reset_games_path %></li>
  <% @games.each do |g| %>
    <li><%= link_to g.data.list_to_s, game_path(g.id) %></li>
  <% end %>
</ul>

app/views/games/show.html.erb
<div class='game'>
  <div class='game-home-link'>
    <%=link_to "#{Poker::BAKA} Poker", games_path %>
  </div>
  <table>
    <tr valign="top">
      <td class='game-current-player-column'>
        <h3>Current Player</h3>
        <%= player_deets(@game.current_player_idx) %>
        <h3>Actions</h3>
        <%= render partial: 'actions' %>
      </td>
      <td>
        <%= game_table %>
      </td>
      <td class='game-stats-column'>
        <%= game_stats %>
      </td>
    </tr>
  </table>
</div>

<hr/>
<%=text_area_tag :game_hand, @game.read_log, size: '100x40' %>

<hr/>
<p><b>Deck:</b><br/><%= show_tiny_cards(@game.deck.cards) %></p>
<p><b>Drawn:</b><br/><%= show_tiny_cards(@game.deck.drawn) %></p>
<p><b>Discarded:</b><%= show_tiny_cards(@game.deck.discarded) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>